### PR TITLE
Feat/faq

### PR DESCRIPTION
**Pull request by sflowers51**
## Types of changes

- [x] New feature (adds functionality)
- [ ] Bug fix (fixes an issue)
- [ ] Breaking changes (causes defects to existing pieces)

## Checklist:

- [x] I have read and complied with the **CONTRIBUTING** document
- [x] The changes I've made follow the existing code style and formatting requirements
- [ ] My changes require updates to the documentation, which I have modified accordingly

### CODE REVIEW

**Comment by asherlloyd** [comment]
You'll need to fill out the missing fields on the pull request:

image

And revert the latest merge from `main` => `feat/faq`. This request should only include the latest changes from the target branch `feat/static-pages`.

**Comment by sflowers51** [comment]
Are there any additions that need to be made to this version of the faq page?

**Comment by asherlloyd** [comment]
@sflowers51 The Git history still doesn't match the target branch; there are changes that would need to be resolved manually. Also, when you are expecting code review feedback, kindly use the "Request review" feature :)

**Comment by sflowers51** [comment]
Thank you for getting back and giving feedback. However, I am still a little uncertain as to the changes needing resolving as well as if I reverted the changes correctly. I also think that the faq will be a component of the home page instead of being a seperate page. Which should I do first, fix the correct issues or go ahead and put it into the home page and than request code review?

**Comment by sflowers51** [comment]
I mostly ask because I resolved changes when reverting and there were issues with that however Kenan and I resolved the conflicts before pushing what the pull request is now.

**Comment by asherlloyd** [comment]
@sflowers51 if you run
```sh
git diff feat/static-pages
```
you will see **changes that are unrelated to your feature** have entered into your branch as a result of merging from a diverged branch, `main`.

One such example is the deletion of `.github/workflows/build.yaml`. If we merged in that change, it would break the build. As such, you need to correct the changes to match the target branch (`feat/static-pages`). I recommend either using Git's `rebase` feature to correct the changes or opening a new, separate merge request with the specific changes for your feature.

**Comment by asherlloyd** [comment]
@sflowers51 please also add the missing context. **Description**, **Reason**, **How this has been tested**, **Screenshots** (if applicable) and anything else that's relevant:

> You'll need to fill out the missing fields on the pull request:
> 
> image
> 
> And revert the latest merge from `main` => `feat/faq`. This request should only include the latest changes from the target branch `feat/static-pages`.

**Pull request closed without merging**
